# mongodb service :- stable network and ip addresses

apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: todo-app
spec:
  selector:
    app: mongo-deployment   # fixed: was "mongo-svc", must match pod label
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP          # fixed: must be uppercase

# default type:- clusterIP (only reachable inside cluster)
# perfect for databases , we never expose DB to internate.